### ISSUE TITLE
Error from Error-Magnifier

### ISSUE THREAD

**Issue by Ockmonek** [eI1on/pz-building-menu#11]
function: tooltipCheckForMaterial -- file: BuildingMenu01_Main.lua line # 357 | MOD: Building Menu
function: canBuildObject -- file: BuildingMenu01_Main.lua line # 457 | MOD: Building Menu
function: updateTooltip -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 76 | MOD: Building Menu
function: render -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 59 | MOD: Building Menu
java.lang.RuntimeException: __concat not defined for operands: null and Brett 11/8 <LINE>
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:805)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
    at zombie.ui.UIElement.render(UIElement.java:1534)
    at zombie.ui.UIElement.render(UIElement.java:1527)
    at zombie.ui.UIManager.render(UIManager.java:446)
    at zombie.gameStates.IngameState.renderFrameUI(IngameState.java:1183)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.gameStates.IngameState.renderframeui(IngameState.java:1172)
    at zombie.gameStates.IngameState.renderInternal(IngameState.java:1324)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.gameStates.IngameState.render(IngameState.java:1271)
    at zombie.gameStates.GameStateMachine.render(GameStateMachine.java:37)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.GameWindow.renderInternal(GameWindow.java:340)
    at zombie.GameWindow.frameStep(GameWindow.java:774)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by eI1on** [comment]
the issue should be fixed now 
[https://github.com/eI1on/pz-building-menu/blob/cb2bd02527b096a61a814fa58a9a3829628b3306/Contents/mods/BuildingMenu/media/lua/client/BuildingMenu01_Main.lua#L376C1-L385C12](url)

**Comment by eI1on** [comment]
the issue should be fixed now
https://github.com/eI1on/pz-building-menu/blob/cb2bd02527b096a61a814fa58a9a3829628b3306/Contents/mods/BuildingMenu/media/lua/client/BuildingMenu01_Main.lua#L376-L386

**Comment by xBuLLeTx95** [comment]
Good time of day. The error appears when you turn on a constant light source from your mod.

`attempted index: addPole of non-table: null
function: perform -- file: ISToggleLight.lua line # 31 | MOD: Building Menu
java.lang.RuntimeException: attempted index: addPole of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
    at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:85)
    at zombie.characters.CharacterTimedActions.LuaTimedActionNew.perform(LuaTimedActionNew.java:104)
    at zombie.characters.IsoGameCharacter.updateInternal(IsoGameCharacter.java:9726)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoGameCharacter.update(IsoGameCharacter.java:9464)
    at zombie.characters.IsoPlayer.updateInternal1(IsoPlayer.java:1943)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoPlayer.update(IsoPlayer.java:1924)
    at zombie.MovingObjectUpdateSchedulerUpdateBucket.update(MovingObjectUpdateSchedulerUpdateBucket.java:79)
    at zombie.MovingObjectUpdateScheduler.update(MovingObjectUpdateScheduler.java:145)
    at zombie.iso.IsoCell.ProcessObjects(IsoCell.java:2955)
    at zombie.iso.IsoCell.updateInternal(IsoCell.java:5750)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoCell.update(IsoCell.java:5696)
    at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3499)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by eI1on** [comment]
fixed here
[https://github.com/eI1on/pz-building-menu/blob/ab5f00ab2ebf7d019b809c0fe020c30970169e53/Contents/mods/BuildingMenu/media/lua/server/BM_ClientCommands.lua#L7](url)
