### ISSUE TITLE
door's bug

### ISSUE THREAD

**Issue by Stiles-Wangs** [eI1on/pz-building-menu#41]
The current problem is that the garage door is not working properly.
After re-enabling it will appear again due to propane replenishment.
No other triggers have been identified.
The error occurred when the mouse was placed on the target. When no click operation occurred, errors began to be reported continuously.
The log is as follows:

`function: tooltipCheckForItem -- file: BuildingMenu01_Main.lua line # 623 | MOD: Building Menu [B41.78]
function: canBuildObject -- file: BuildingMenu01_Main.lua line # 748 | MOD: Building Menu [B41.78]
function: getTooltipContent -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 213 | MOD: Building Menu [B41.78]
function: updateTooltipContent -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 239 | MOD: Building Menu [B41.78]
function: updateTooltip -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 112 | MOD: Building Menu [B41.78]
function: render -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 62 | MOD: Building Menu [B41.78]
java.lang.RuntimeException: __len not defined for operand
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaUtil.luaAssert(KahluaUtil.java:70)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:748)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
    at zombie.ui.UIElement.render(UIElement.java:1534)
    at zombie.ui.UIElement.render(UIElement.java:1527)
    at zombie.ui.UIManager.render(UIManager.java:446)
    at zombie.gameStates.IngameState.renderFrameUI(IngameState.java:1183)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.gameStates.IngameState.renderframeui(IngameState.java:1172)
    at zombie.gameStates.IngameState.renderInternal(IngameState.java:1324)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.gameStates.IngameState.render(IngameState.java:1271)
    at zombie.gameStates.GameStateMachine.render(GameStateMachine.java:37)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.GameWindow.renderInternal(GameWindow.java:340)
    at zombie.GameWindow.frameStep(GameWindow.java:774)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by eI1on** [comment]
This bug has been fixed in #40 and will be implemented in the next update
