### ISSUE TITLE
An error occurs when trying to make metal-related crafting.

### ISSUE THREAD

**Issue by Mark-0154** [eI1on/pz-building-menu#42]
Wood-related production proceeds normally, but when metal-related production is attempted, an error log occurs as shown below.

function: tooltipCheckForItem -- file: BuildingMenu01_Main.lua line # 623 | MOD: Building Menu [B41.78]
function: canBuildObject -- file: BuildingMenu01_Main.lua line # 748 | MOD: Building Menu [B41.78]
function: getTooltipContent -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 213 | MOD: Building Menu [B41.78]
function: updateTooltipContent -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 239 | MOD: Building Menu [B41.78]
function: updateTooltip -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 112 | MOD: Building Menu [B41.78]
function: render -- file: BuildingMenu00a_ISBuildingMenuUI.lua line # 62 | MOD: Building Menu [B41.78]
java.lang.RuntimeException: __len not defined for operand
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaUtil.luaAssert(KahluaUtil.java:70)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:748)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
    at zombie.ui.UIElement.render(UIElement.java:1534)
    at zombie.ui.UIElement.render(UIElement.java:1527)
    at zombie.ui.UIManager.render(UIManager.java:446)
    at zombie.gameStates.IngameState.renderFrameUI(IngameState.java:1183)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.gameStates.IngameState.renderframeui(IngameState.java:1172)
    at zombie.gameStates.IngameState.renderInternal(IngameState.java:1324)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.gameStates.IngameState.render(IngameState.java:1271)
    at zombie.gameStates.GameStateMachine.render(GameStateMachine.java:37)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.GameWindow.renderInternal(GameWindow.java:340)
    at zombie.GameWindow.frameStep(GameWindow.java:774)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)

I am attaching a screenshot of the error.

![108600_3](https://github.com/user-attachments/assets/391fb326-81f0-4130-a543-a52bb7292604)
![108600_4](https://github.com/user-attachments/assets/9a272545-ec7b-4044-a078-3f5bb713215b)
![108600_5](https://github.com/user-attachments/assets/0be88559-1513-4f7b-aeb7-ad4aee4820c1)

**Comment by Mark-0154** [comment]
I confirmed something new. If you put the materials in the inventory and start crafting, the process will proceed normally, but if you try to craft with materials placed on the floor, an error will occur.

**Comment by eI1on** [comment]
This bug has been fixed in #40 and will be implemented in the next update
